name: RentHouse
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  google_fonts: 
  intl: ^0.17.0
  fluttertoast: ^8.0.7
  photo_view: ^0.11.1
  image_picker: ^0.6.0+17
  firebase_storage: 
  firebase_database: 
  flutter_bloc: 
  equatable:
  meta:
  shared_preferences: ^2.0.6
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  rxdart: ^0.18.0
  url_launcher: ^5.5.2
  flutter_form_builder: 
  image_picker_web: ^1.0.9
  path: ^1.7.0
  flutter_spinkit: ^5.1.0
  uuid: 
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/img/icoHome.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
 